### ISSUE TITLE
FE Adjust match proposal Layout(Collapsed view)

### ISSUE THREAD

**Issue by agent-carvajal** [agent-carvajal/grant-connect#40]
Use Flex properties to adjust the layout of the match proposal cards

How it looks:

![Image](https://github.com/agent-carvajal/grant-connect/assets/146678543/13a0e0cd-4ffc-4c44-941b-4990ede84eb8)

How it should look:
![Image](https://github.com/agent-carvajal/grant-connect/assets/146678543/60ec4ace-b922-470b-b696-53efb1c8738c)

**Comment by ValleA242** [comment]
Testing good on my end, looks like you took care of this earlier today. Let me know if any further changes are needed.
